FROM apache/airflow:2.7.1

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    dbt-postgres\
    requests \
    psycopg2-binary \
    python-dotenv \
    s3fs \ 
    pandas \